### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by DanceParty** [Tyriar/hangul-romanization#3]
```
Error: Cannot find module './conversionSystems/revisedRomanizationOfKorean'
2017-05-09T02:49:42.190635+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-05-09T02:49:42.190636+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-05-09T02:49:42.190636+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-05-09T02:49:42.190637+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-05-09T02:49:42.190638+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/hangul-romanization/dist/index.js:5:37)
2017-05-09T02:49:42.190639+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-05-09T02:49:42.190640+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-05-09T02:49:42.190639+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-05-09T02:49:42.190641+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-05-09T02:49:42.190640+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-05-09T02:49:42.310697+00:00 heroku[web.1]: Process exited with status 1
2017-05-09T02:49:42.341305+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-09T02:49:42.342039+00:00 heroku[web.1]: State changed from crashed to starting
2017-05-09T02:49:45.548971+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-05-09T02:49:48.901575+00:00 heroku[web.1]: Process exited with status 1
2017-05-09T02:49:48.918700+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-09T02:49:48.795840+00:00 app[web.1]: module.js:471
2017-05-09T02:49:48.795854+00:00 app[web.1]:     throw err;
```

**Comment by DanceParty** [comment]
Adding file extensions to the modules fixed this for me, so I am going to submit a pull request. Let me know if I did it incorrectly as I am new.

Thanks for the great package!

**Comment by Tyriar** [comment]
Hi @jkd65, I had a look at this. The reason for the error is that all the files weren't getting published to npm properly. Downloading the latest should work now, apologies for the delay 😃
